# Fuente (Asegúrate de tener instalada ttf-jetbrains-mono-nerd)
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Transparencia (0.0 es invisible, 1.0 es sólido)
background_opacity 0.85

# Estilo de la ventana
window_padding_width 10

# Color del cursor
cursor #ff00ff
